### ISSUE TITLE
Original error: support_1.imageUtil.getJimpImage is not a function

### ISSUE THREAD

**Issue by lizwangying** [jlipps/appium-ocr-plugin#7]
Hello Dear Author Jlipps:

I've followed your steps on readme.md. Found this error looks like can't find a method in the plugin, this is my log : 
```
2023-07-20T03:20:31.503Z INFO webdriver: COMMAND findElements("accessibility id", "Login Screen")
2023-07-20T03:20:31.503Z INFO webdriver: [POST] http://127.0.0.1:4723/session/ab873008-7c56-45ae-a024-1b31b3660818/elements
2023-07-20T03:20:31.504Z INFO webdriver: DATA { using: 'accessibility id', value: 'Login Screen' }
2023-07-20T03:20:31.640Z INFO webdriver: RESULT [
  {
    'element-6066-11e4-a52e-4f735466cecf': '00000000-0000-01d2-ffff-ffff00000020',
    ELEMENT: '00000000-0000-01d2-ffff-ffff00000020'
  }
]
2023-07-20T03:20:44.435Z INFO webdriver: COMMAND getOcrText()
2023-07-20T03:20:44.437Z INFO webdriver: COMMAND getOcrText()
2023-07-20T03:20:44.438Z INFO webdriver: [POST] http://127.0.0.1:4723/session/ab873008-7c56-45ae-a024-1b31b3660818/appium/ocr
2023-07-20T03:20:45.072Z ERROR webdriver: Request failed with status 500 due to unknown error: An unknown server-side error occurred while processing the command. Original error: support_1.imageUtil.getJimpImage is not a function

unknown error: An unknown server-side error occurred while processing the command. Original error: support_1.imageUtil.getJimpImage is not a function
    at getErrorFromResponseBody (file:///C:/Users/Administrator/PycharmProjects/appium-ocr-plugin/node_modules/webdriver/build/utils.js:194:12)
    at NodeJSRequest._request (file:///C:/Users/Administrator/PycharmProjects/appium-ocr-plugin/node_modules/webdriver/build/request/index.js:164:23)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Browser.wrapCommandFn (file:///C:/Users/Administrator/PycharmProjects/appium-ocr-plugin/node_modules/@wdio/utils/build/shim.js:72:29)
``` 
And this is my orc version: ocr@0.1.3, My appium sever log :
``` 
 ✘ Administrator  ~  appium --use-plugins="images,ocr" --relaxed-security --allow-cors -p 4723

[Appium] Attempting to load plugin images...
[debug] [Appium] Requiring plugin at C:\Users\Administrator\.appium\node_modules\@appium\images-plugin
[Appium] Attempting to load plugin ocr...
[debug] [Appium] Requiring plugin at C:\Users\Administrator\.appium\node_modules\appium-ocr-plugin
[Appium] Welcome to Appium v2.0.0-rc.5
[Appium] Non-default server args:
[Appium] {
[Appium]   allowCors: true,
[Appium]   relaxedSecurityEnabled: true,
[Appium]   usePlugins: [
[Appium]     'images',
[Appium]     'ocr'
[Appium]   ]
[Appium] }
[Appium] Attempting to load driver uiautomator2...
[debug] [Appium] Requiring driver at C:\Users\Administrator\.appium\node_modules\appium-uiautomator2-driver
[Appium] You have enabled CORS requests from any host. Be careful not to visit sites which could maliciously try to start Appium sessions on your machine
[Appium] Appium REST http interface listener started on http://0.0.0.0:4723
[Appium] You can provide the following URLS in your client code to connect to this server:
[Appium]        http://192.168.50.84:4723/
[Appium]        http://10.0.85.2:4723/
[Appium]        http://127.0.0.1:4723/ (only accessible from the same host)
[Appium] Available drivers:
[Appium]   - uiautomator2@2.29.2 (automationName 'UiAutomator2')
[Appium] Available plugins:
[Appium]   - images@2.1.2 (ACTIVE)
[Appium]   - device-farm@8.2.0
[Appium]   - appium-dashboard@v2.0.2
[Appium]   - ocr@0.1.3 (ACTIVE)
[Appium]   - gestures@3.0.0
```

How can I fix this error ? Did I do something wrong ? 

BTW，can I use this plugin in java client ? Because I can't find a super class role works like `from appium.webdriver.webdriver import ExtensionBase` , and one of the java client AndroidDriver constructor has `HttpCommandExecutor` maybe this is the one to add ocr extension ? Can you give me some demo code please?  
![image](https://github.com/jlipps/appium-ocr-plugin/assets/13509775/e9dbcd03-9007-4000-a873-34a9ccacf5fe)

**Comment by jlipps** [comment]
Please try the latest version of the plugin. This issue has already been fixed.

**Comment by lizwangying** [comment]
Thanks 👍
